allprojects {
    repositories {
        google()
        mavenCentral()
        flatDir {
            dirs '../libs/', '../', "$rootDir/libs" // Folders to look for jar & aar libraries
        }
        maven {
            url "${project(':background_fetch').projectDir}/libs"
        }
    }
}

rootProject.buildDir = '../build'
subprojects {
    project.buildDir = "${rootProject.buildDir}/${project.name}"
}
subprojects {
    project.evaluationDependsOn(':app')
}

tasks.register("clean", Delete) {
    delete rootProject.buildDir
}
